
export const environment = {
  production: false,
  base: 'http://localhost:3001/#/student/',
  baseUrlTeacher: 'http://localhost:3001',
  apiUrlTeacher: 'https://ecmanagementteaching-escuela-judicial.apps.revisados-attt.8ckj.p1.openshiftapps.com/api/v1/Teacher/',
  apiUrl: 'https://identity-ej-escuela-judicial.apps.revisados-attt.8ckj.p1.openshiftapps.com/api/v1/Account/',
  apiUrlRol: 'https://identity-ej-escuela-judicial.apps.revisados-attt.8ckj.p1.openshiftapps.com/api/v1/',
  apiUrlSchedule: "https://eccurriculummanagement-escuela-judicial.apps.revisados-attt.8ckj.p1.openshiftapps.com/api/v1/",
  ConsultaDocentes: 'https://ecmanagementteaching-escuela-judicial.apps.revisados-attt.8ckj.p1.openshiftapps.com/api/v1/',
  consultaEstudiante: 'https://ecinscriptionservice-escuela-judicial.apps.revisados-attt.8ckj.p1.openshiftapps.com/api/Cedula/DataqueryCedula/GetDataCedula/',
  consultaPlanesAprobados: 'https://efcurriculummanagement-escuela-judicial.apps.revisados-attt.8ckj.p1.openshiftapps.com/api/v1/AnnualPlan/GetAll?StatusId=5',
  ConsultaMallaCurrcularByPlan: 'https://efcurriculummanagement-escuela-judicial.apps.revisados-attt.8ckj.p1.openshiftapps.com/api/v1/AnnualPlan/GetDegreeCurriculumDesignsBy?AnnualPlanId=',
  apiEC: "https://ecinscriptionservice-escuela-judicial.apps.revisados-attt.8ckj.p1.openshiftapps.com/api/v1/",
  apiForo: "https://foro-escuela-judicial.apps.revisados-attt.8ckj.p1.openshiftapps.com/api/v1/",
  apiCatalogs: 'https://ecinscriptionservice-escuela-judicial.apps.revisados-attt.8ckj.p1.openshiftapps.com/api/',
  apiUrlEF: 'https://isjupefcurriculummanagementservice.azurites.net/api/v1/Subject/',
  apiUrlEC: 'https://eccurriculummanagement-escuela-judicial.apps.revisados-attt.8ckj.p1.openshiftapps.com/api/v1/Activity/',
  apiEF: "https://efcurriculummanagement-escuela-judicial.apps.revisados-attt.8ckj.p1.openshiftapps.com/api/v1/",
  apiUrlDocument: 'https://ecmanagementteaching-escuela-judicial.apps.revisados-attt.8ckj.p1.openshiftapps.com/api/v1/RequiredDocument/',
  apiIntranet: 'https://eintranetregistroacademico-escuela-judicial.apps.revisados-attt.8ckj.p1.openshiftapps.com/',
  apiUrlSubjectTask: "https://eintranetregistroacademico-escuela-judicial.apps.revisados-attt.8ckj.p1.openshiftapps.com/SearchSubjectTask",
  apiEira: 'https://eintranetregistroacademico-escuela-judicial.apps.revisados-attt.8ckj.p1.openshiftapps.com/',
  apiDocument: 'https://documentservices-escuela-judicial.apps.revisados-attt.8ckj.p1.openshiftapps.com/api/v1/',
  apiExtUrlDependencies: 'https://ecinscriptionservice-escuela-judicial.apps.revisados-attt.8ckj.p1.openshiftapps.com/api/Cedula/DataqueryCedula/getDepInfo',
  apiSharedUrl: 'https://shared-escuela-judicial.apps.revisados-attt.8ckj.p1.openshiftapps.com/api/v1/Shared/',
};
