export const environment = {
  production: false,
  base: 'https://isjup.3techdemos.com/#/student/',
  apiUrlTeacher: 'https://ecmanagementteaching-escuela-judicial.apps.revisados-attt.8ckj.p1.openshiftapps.com/api/v1/Teacher/',
  apiUrl: 'https://isjupauthenticationservice.azurewebsites.net/api/v1/account/',
  apiUrlSchedule: "https://isjupeccurriculummanagementservice.azurewebsites.net/api/v1/",
  ConsultaDocentes: 'https://ecmanagementteaching-escuela-judicial.apps.revisados-attt.8ckj.p1.openshiftapps.com/api/v1/',
  consultaEstudiante: 'https://ecinscriptionservice-escuela-judicial.apps.revisados-attt.8ckj.p1.openshiftapps.com/api/Cedula/DataqueryCedula/GetDataCedula/',
  consultaPlanesAprobados: 'https://isjupefcurriculummanagementservice.azurewebsites.net/api/v1/AnnualPlan/GetAll?StatusId=5',
  ConsultaMallaCurrcularByPlan: 'https://isjupefcurriculummanagementservice.azurewebsites.net/api/v1/AnnualPlan/GetDegreeCurriculumDesignsBy?AnnualPlanId=',
  apiEC: "https://ecinscriptionservice-escuela-judicial.apps.revisados-attt.8ckj.p1.openshiftapps.com/api/v1/",
  apiUrlEF: 'https://isjupefcurriculummanagementservice.azurewebsites.net/api/v1/Subject/',
  apiUrlEC: 'https://isjupeccurriculummanagementservice.azurewebsites.net/api/v1/Activity/',
  apiEF: "https://isjupefcurriculummanagementservice.azurewebsites.net/api/v1/",
  apiUrlDocument: 'https://ecmanagementteaching-escuela-judicial.apps.revisados-attt.8ckj.p1.openshiftapps.com/api/v1/RequiredDocument/',
};
