
export const environment = {

  production: false,
  base: 'http://erp.organo-judicial.com/#/student/',
  baseUrlTeacher: 'http://erp.organo-judicial.com',
  Key:'ZUNMO8BbyYJIxx0pg5l9xFZEuCuix2yr7cfqfw0LAT42niZJm3SMNmtvZAwW4jLT', //Key de encriptacion

  

  // apiUrlTeacher: 'https://ecmanagementteaching-escuelajudicial-isjup.organojudicial.gob.pa:5502/api/v1/Teacher/',
  // apiUrl: 'https://identity-escuelajudicial-isjup.organojudicial.gob.pa:5500/api/v1/Account/',
  // apiUrlRol: 'https://identity-escuelajudicial-isjup.organojudicial.gob.pa:5500/api/v1/',
  // apiUrlSchedule: "https://eccurriculummanagement-escuelajudicial-isjup.organojudicial.gob.pa:5505/api/v1/",
  // ConsultaDocentes: 'https://ecmanagementteaching-escuelajudicial-isjup.organojudicial.gob.pa:5502/api/v1/',
  // consultaEstudiante: 'https://identity-escuelajudicial-isjup.organojudicial.gob.pa:5501/api/Cedula/DataqueryCedula/GetDataCedula/',
  // consultaPlanesAprobados: 'https://efcurriculummanagement-escuelajudicial-isjup.organojudicial.gob.pa:5504/api/v1/AnnualPlan/GetAll?StatusId=5',
  // ConsultaMallaCurrcularByPlan: 'https://efcurriculummanagement-escuelajudicial-isjup.organojudicial.gob.pa:5504/api/v1/AnnualPlan/GetDegreeCurriculumDesignsBy?AnnualPlanId=',
  // apiEC: "https://identity-escuelajudicial-isjup.organojudicial.gob.pa:5501/api/v1/",
  // apiForo: "https://foroservices-escuelajudicial-isjup.organojudicial.gob.pa:5503/api/v1/",
  // apiCatalogs: 'https://identity-escuelajudicial-isjup.organojudicial.gob.pa:5501/api/',
  // apiUrlEF: 'https://efcurriculummanagement-escuelajudicial-isjup.organojudicial.gob.pa:5504/api/v1/Subject/',
  // apiUrlEC: 'https://eccurriculummanagement-escuelajudicial-isjup.organojudicial.gob.pa:5505/api/v1/Activity/',
  // apiEF: "https://efcurriculummanagement-escuelajudicial-isjup.organojudicial.gob.pa:5504/api/v1/",
  // apiUrlDocument: 'https://ecmanagementteaching-escuelajudicial-isjup.organojudicial.gob.pa:5502/api/v1/RequiredDocument/',
  // apiIntranet: 'https://eintranetregistroacademico-escuelajudicial-isjup.organojudicial.gob.pa:5507/',
  // apiUrlSubjectTask: "https://eintranetregistroacademico-escuelajudicial-isjup.organojudicial.gob.pa:5507/SearchSubjectTask",
  // apiEira: 'https://eintranetregistroacademico-escuelajudicial-isjup.organojudicial.gob.pa:5507/',
  // apiDocument: 'https://documentservices-escuelajudicial-isjup.organojudicial.gob.pa:5508/api/v1/',
  // apiExtUrlDependencies: 'https://identity-escuelajudicial-isjup.organojudicial.gob.pa:5501/api/Cedula/DataqueryCedula/getDepInfo',
  // apiSharedUrl: 'https://shared-escuelajudicial-isjup.organojudicial.gob.pa:5509/api/v1/Shared/',
  // apiJobs: 'https://jobboard-escuelajudicial-isjup.organojudicial.gob.pa:5506/api/v1/',
  // apiUrlTreasury: 'https://tresury-escuelajudicial-isjup.organojudicial.gob.pa:5510/api/v1/',
  // apisignature: 'https://portafirma-escuelajudicial-isjup.organojudicial.gob.pa:5511/api/v1/'

  apiUrlTeacher: 'https://ecmanagementteaching-escuela-judicial.apps.revisados-attt.8ckj.p1.openshiftapps.com/api/v1/Teacher/',
  apiUrl: 'http://localhost:7212/api/v1/Account/',
  apiUrlRol: 'http://localhost:7212/api/v1/',
  apiUrlSchedule: "http://localhost:7179/api/v1/",
  ConsultaDocentes: 'https://ecmanagementteaching-escuela-judicial.apps.revisados-attt.8ckj.p1.openshiftapps.com/api/v1/',
  consultaEstudiante: 'https://ecinscriptionservice-escuela-judicial.apps.revisados-attt.8ckj.p1.openshiftapps.com/api/Cedula/DataqueryCedula/GetDataCedula/',
  consultaPlanesAprobados: 'https://efcurriculummanagement-escuela-judicial.apps.revisados-attt.8ckj.p1.openshiftapps.com/api/v1/AnnualPlan/GetAll?StatusId=5',
  ConsultaMallaCurrcularByPlan: 'https://efcurriculummanagement-escuela-judicial.apps.revisados-attt.8ckj.p1.openshiftapps.com/api/v1/AnnualPlan/GetDegreeCurriculumDesignsBy?AnnualPlanId=',
  apiEC: "https://ecinscriptionservice-escuela-judicial.apps.revisados-attt.8ckj.p1.openshiftapps.com/api/v1/",
  apiForo: "https://foro-escuela-judicial.apps.revisados-attt.8ckj.p1.openshiftapps.com/api/v1/",
  apiCatalogs: 'https://ecinscriptionservice-escuela-judicial.apps.revisados-attt.8ckj.p1.openshiftapps.com/api/',
  apiUrlEF: 'https://isjupefcurriculummanagementservice.azurites.net/api/v1/Subject/',
  apiUrlEC: 'http://localhost:7179/api/v1/Activity/',
  apiEF: "https://efcurriculummanagement-escuela-judicial.apps.revisados-attt.8ckj.p1.openshiftapps.com/api/v1/",
  apiUrlDocument: 'https://ecmanagementteaching-escuela-judicial.apps.revisados-attt.8ckj.p1.openshiftapps.com/api/v1/RequiredDocument/',
  apiIntranet: 'https://eintranetregistroacademico-escuela-judicial.apps.revisados-attt.8ckj.p1.openshiftapps.com/',
  apiUrlSubjectTask: "https://eintranetregistroacademico-escuela-judicial.apps.revisados-attt.8ckj.p1.openshiftapps.com/SearchSubjectTask",
  apiEira: 'https://eintranetregistroacademico-escuela-judicial.apps.revisados-attt.8ckj.p1.openshiftapps.com/',
  apiDocument: 'https://documentservices-escuela-judicial.apps.revisados-attt.8ckj.p1.openshiftapps.com/api/v1/',
  apiExtUrlDependencies: 'https://ecinscriptionservice-escuela-judicial.apps.revisados-attt.8ckj.p1.openshiftapps.com/api/Cedula/DataqueryCedula/getDepInfo',
  apiSharedUrl: 'https://shared-escuela-judicial.apps.revisados-attt.8ckj.p1.openshiftapps.com/api/v1/Shared/',
  apiJobs: 'https://jobboard-escuela-judicial.apps.revisados-attt.8ckj.p1.openshiftapps.com/api/v1/',
  apiUrlTreasury: 'http://localhost:5032/api/v1/',
  apisignature: 'https://treasuryservice-escuela-judicial.apps.revisados-attt.8ckj.p1.openshiftapps.com/api/v1/'
};
