import { RouteInfo } from './sidebar.metadata';
export const ROUTES: RouteInfo[] = [
  {
    path: '/dashboard/dashboard1',
    title: 'Panel control',
    iconType: 'feather',
    icon: 'calendar',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    Role: 'Administrador',
    submenu: [],
  },

  //incripción
  {
    path: '',
    title: 'Admisión',
    iconType: 'feather',
    icon: 'calendar',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    Role: 'Administrador',
    submenu: [
      {
        path: '/admission/schedule-activities-list',
        title: 'Cronograma de actividades',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        Role: 'Administrador',
        submenu: [],
      },
      {
        path: '/admission/AnnualPlan',
        title: 'Cronograma Anual EF',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        Role: 'Administrador',
        submenu: [],
      },
    ]
  },

  // Incripcion
  {
    path: 'admission/',
    title: 'Inscripciones',
    iconType: '',
    icon: 'user-check',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    Role: 'Administrador',
    submenu: [
      {
        path: 'admission/schedule-list',
        title: 'BackOffice',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        Role: 'Administrador',
        submenu: [],
      },
      {
        path: 'admission/activity-participants-list',
        title: 'Participantes',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        Role: 'Administrador',
        submenu: [],
      },
    ],
  },

  // Formulario EF
  {
    path: 'admission/',
    title: 'Inscripciones EF',
    iconType: '',
    icon: 'user-check',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    Role: 'Administrador',
    submenu: [
      {
        path: 'admission/form-ef',
        title: 'BackOffice',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        Role: 'Administrador',
        submenu: [],
      },
      {
        path: 'admission/list-inscriptions-plans',
        title: 'Participantes',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        Role: 'Administrador',
        submenu: [],
      },
    ],
  },
  {
    path: '/dashboard/dashboard1',
    title: 'Panel control',
    iconType: 'feather',
    icon: 'calendar',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    Role: 'Director',
    submenu: [],
  },
  //aprobaciones
  {
    path: '',
    title: 'Aprobaciones',
    iconType: 'feather',
    icon: 'check-circle',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    Role: 'Director',
    submenu: [
      {
        path: 'admission/list-curriculum-approve',
        title: 'Cronograma de actividades',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        Role: 'Director',
        submenu: [],
      },
      {
        path: 'admission/list-rooms-approve',
        title: 'Solicitud de Salones',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        Role: 'Director',
        submenu: [],
      },
      {
        path: 'admission/list-post-approve',
        title: 'Solicitud de Afiche',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        Role: 'Director',
        submenu: [],
      },
    ],
  },

  //ajustes EC
  {
    path: "",
    title: "Ajustes",
    iconType: "",
    icon: "database",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    Role: 'Administrador',
    submenu: [
      {
        path: "/admission/source-funds-list",
        title: "Origen de fondos",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        Role: 'Administrador',
        submenu: []
      }, {
        path: "/admission/activity-ubication-list",
        title: "Ubicación Actividades",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        Role: 'Administrador',
        submenu: []
      },

      {
        path: "/admission/modality-list",
        title: "Modalidad",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        Role: 'Administrador',
        submenu: []
      },
      {
        path: "/admission/reason-list",
        title: "Motivo",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        Role: 'Administrador',
        submenu: []
      },
      {
        path: "/admission/type-activity-list",
        title: "Tipo de actividad",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        Role: 'Administrador',
        submenu: []
      },
      {
        path: "/admission/supplies-list",
        title: "Insumos",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        Role: 'Administrador',
        submenu: []
      },
      {
        path: "/admission/lounge-list",
        title: "Salón",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        Role: 'Administrador',
        submenu: []
      },
      {
        path: "/admission/documentation-required-list",
        title: "Documentación",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        Role: 'Administrador',
        submenu: []
      },
      {
        path: "/admission/status-list",
        title: "Estados",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        Role: 'Administrador',
        submenu: []
      },
      {
        path: "/admission/cooperating-organization",
        title: "Organización cooperativa",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        Role: 'Administrador',
        submenu: []
      },
      {
        path: "/admission/cooperating-organization",
        title: "Crear Programa",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        Role: 'Administrador',
        submenu: []
      },
      {
        path: "/admission/required-document-list",
        title: "Documentos",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        Role: 'Administrador',
        submenu: []
      },


    ]
  },

  //Ajustes EF
  {
    path: "",
    title: "Ajustes EF",
    iconType: "",
    icon: "database",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    Role: 'Administrador',
    submenu: [
      {
        path: "/admission/carreras",
        title: "Carreras",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        Role: 'Administrador',
        submenu: []
      },
      {
        path: "/admission/asignaturas",
        title: "Asignaturas",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        Role: 'Administrador',
        submenu: []
      },
      {
        path: "/admission/documentos-requeridos",
        title: "Documentos requeridos",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        Role: 'Administrador',
        submenu: []
      },
      {
        path: "/admission/modo-estudios",
        title: "Modo de estudios",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        Role: 'Administrador',
        submenu: []
      },
      {
        path: "/admission/salones",
        title: "Salones",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        Role: 'Administrador',
        submenu: []
      },
      {
        path: "/admission/estado",
        title: "Estados",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        Role: 'Administrador',
        submenu: []
      },
    ],
  },
  //aprobaciones
  {
    path: '',
    title: 'Aprobaciones EF',
    iconType: 'feather',
    icon: 'check-circle',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    Role: 'Director',
    submenu: [
      {
        path: 'admission/approved-annualplan',
        title: 'Plan Anual',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        Role: 'Director',
        submenu: [],
      },
      {
        path: 'admission/approved-degree',
        title: 'Mallas Curriculares',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        Role: 'Director',
        submenu: [],
      },
      {
        path: 'admission/approved-poster',
        title: 'Solicitud de Afiche',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        Role: 'Director',
        submenu: [],
      },
    ],
  },
  //gestion docente.
  {
    path: "",
    title: "Gestión Docente",
    iconType: "feather",
    icon: "lock",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    Role: 'Administrador',
    submenu: [
      {
        path: "/teaching-management/teacher-list",
        title: "Docentes",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        Role: 'Administrador',
        submenu: [],
      },
      {
        path: "/teaching-management/teacher-history-list",
        title: "Historial docente",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        Role: 'Administrador',
        submenu: [],
      }
    ]
  },

  //Seguridad
  {
    path: '',
    title: 'Seguridad',
    iconType: 'feather',
    icon: 'lock',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    Role: 'Administrador',
    submenu: [
      {
        path: '/security/user-list',
        title: 'Usuario',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        Role: 'Administrador',
        submenu: [],
      },
      {
        path: '/security/role-list',
        title: 'Rol',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        Role: 'Administrador',
        submenu: [],
      },
    ],
  },
  //estudiante

  {
    path: '/dashboard/dashboard1',
    title: 'Panel control',
    iconType: 'feather',
    icon: 'calendar',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    Role: 'Estudiante',
    submenu: [],
  },
  {
    path: '',
    title: 'Matricula',
    iconType: 'feather',
    icon: 'table',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    Role: 'Estudiante',
    submenu: [
      {
        path: '/security/user-list',
        title: 'Matricula',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        Role: 'Estudiante',
        submenu: [],
      },
      {
        path: '/security/role-list',
        title: 'Pre-Matricula',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        Role: 'Estudiante',
        submenu: [],
      },
    ],
  },

  {
    path: '',
    title: 'Historial',
    iconType: 'feather',
    icon: 'hard-drive',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    Role: 'Estudiante',
    submenu: [
      {
        path: '/security/user-list',
        title: 'Creditos no Oficiales',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        Role: 'Estudiante',
        submenu: [],
      },
      {
        path: '/security/role-list',
        title: 'Notas',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        Role: 'Estudiante',
        submenu: [],
      },
      {
        path: '/security/role-list',
        title: 'Plan de Estudio',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        Role: 'Estudiante',
        submenu: [],
      },
      {
        path: '/security/role-list',
        title: 'Asistencia',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        Role: 'Estudiante',
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'Solicitudes',
    iconType: 'feather',
    icon: 'folder',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    Role: 'Estudiante',
    submenu: [
      {
        path: '/security/user-list',
        title: 'Retiro o Reingresos',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        Role: 'Estudiante',
        submenu: [],
      },
      {
        path: '/security/role-list',
        title: 'Solicitudes Varias',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        Role: 'Estudiante',
        submenu: [],
      },
    ],
  },

];
